# Generated by Django 6.1 on 2026-08-30 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PAGE_VIEW', 'Vue de page'), ('APP_OPEN', 'Ouverture application'), ('QUIZ_START', 'Début quiz'), ('QUIZ_COMPLETE', 'Quiz terminé'), ('DAILY_QUOTE_VIEW', 'Citation consultée'), ('EVENT_VIEW', 'Événement consulté'), ('NOTIFICATION_OPEN', 'Notification ouverte'), ('OFFLINE', 'Passage hors ligne'), ('ONLINE', 'Retour en ligne'), ('PWA_INSTALL', 'Installation PWA'), ('CUSTOM', 'Événement personnalisé')], max_length=50)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('client_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
