# Generated by Django 6.1 on 2026-08-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('MEETING', 'Réunion'), ('PRAYER', 'Réunion de prière'), ('STUDY', "Cercle d'étude"), ('CHILDREN', "Classe d'enfants"), ('YOUTH', 'Groupe de jeunes'), ('COMMUNITY', 'Activité communautaire'), ('SERVICE', 'Acte de service'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('responsible', models.CharField(blank=True, max_length=200)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
