# Generated by Django 6.1 on 2026-08-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalevent',
            name='event_type',
            field=models.CharField(choices=[('MEETING', 'Réunion'), ('ACTIVITY', 'Activité'), ('DEVOTIONAL', 'Réunion de prière'), ('STUDY', "Cercle d'étude"), ('FEAST', 'Fête des Dix-Neuf Jours'), ('HOLY_DAY', 'Jour saint'), ('OTHER', 'Autre')], default='OTHER', max_length=30),
        ),
    ]
