# Generated by Django 6.1 on 2026-08-09 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_imports', '0001_initial'),
        ('personal_events', '0002_alter_personalevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalevent',
            name='source_detected_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_event', to='document_imports.detectedevent'),
        ),
    ]
