# Generated by Django 6.1 on 2026-08-09 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='document_imports/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'Word'), ('XLSX', 'Excel'), ('IMAGE', 'Image'), ('UNKNOWN', 'Inconnu')], default='UNKNOWN', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'Traitement'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échec')], default='PENDING', max_length=20)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('has_tables', models.BooleanField(default=False)),
                ('has_images', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='document_imports.documentimport')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='DetectedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_date_end', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('responsible', models.CharField(blank=True, default='', max_length=255)),
                ('objective', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('work_suspension', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('DETECTED', 'Détecté'), ('REVIEW', 'À vérifier'), ('CONFIRMED', 'Confirmé'), ('REJECTED', 'Rejeté')], default='DETECTED', max_length=20)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('source_reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_events', to='document_imports.documentimport')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_events', to='document_imports.documentpage')),
            ],
            options={
                'ordering': ['event_date', 'start_time', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='document_images/%Y/%m/')),
                ('image_index', models.PositiveIntegerField(default=0)),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='document_imports.documentpage')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('normalized_value', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(choices=[('TEXT', 'Texte'), ('TABLE', 'Tableau'), ('IMAGE', 'Image'), ('OCR', 'OCR'), ('AI', 'IA')], default='TEXT', max_length=20)),
                ('confidence', models.FloatField(default=1.0)),
                ('source_reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_information', to='document_imports.documentimport')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_information', to='document_imports.documentpage')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_index', models.PositiveIntegerField(default=0)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='document_imports.documentpage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='documentpage',
            constraint=models.UniqueConstraint(fields=('document', 'page_number'), name='unique_document_page'),
        ),
    ]
