# Generated by Django 6.1 on 2026-08-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedevent',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detectedevent',
            name='reminder_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
