# Generated by Django 6.1 on 2026-08-19 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'event_source', 'event_code'], name='notificatio_user_id_aa0a40_idx'),
        ),
    ]
