# Generated by Django 6.1 on 2026-08-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('HOLY_DAY', 'Jour saint'), ('FEAST', 'Fête des 19 jours'), ('AYYAM_I_HA', 'Ayyám-i-Há'), ('FAST', 'Période du Jeûne'), ('NEW_YEAR', 'Nouvel An bahá’í'), ('OTHER', 'Autre')], max_length=30)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_holy_day', models.BooleanField(default=False)),
                ('is_work_suspended', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField()),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('event_type', 'date', 'year'), name='unique_bahai_calendar_event')],
            },
        ),
    ]
