# Generated by Django 6.1 on 2026-08-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('moment', models.CharField(choices=[('MORNING', 'Matin'), ('EVENING', 'Soir')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
