# Generated by Django 6.1 on 2026-08-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyquote',
            options={'ordering': ['date', 'moment']},
        ),
        migrations.AddIndex(
            model_name='dailyquote',
            index=models.Index(fields=['date', 'moment'], name='daily_quote_date_c9f450_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyquote',
            index=models.Index(fields=['is_active', 'date'], name='daily_quote_is_acti_eeb899_idx'),
        ),
    ]
