# Generated by Django 6.1 on 2026-08-08 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('language', models.CharField(default='fr', max_length=10)),
                ('timezone', models.CharField(default='Africa/Brazzaville', max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('VISITOR', 'Visiteur'), ('MEMBER', 'Membre'), ('ANIMATOR', 'Animateur'), ('RESPONSIBLE', 'Responsable'), ('COORDINATOR', 'Coordinateur'), ('SECRETARY', 'Secrétaire'), ('ADMIN', 'Administrateur')], default='MEMBER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
