# Generated by Django 6.1 on 2026-08-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quiz_sessions', to='quiz.quizquestion'),
        ),
    ]
