# Generated by Django 6.1 on 2026-08-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizsession_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogress',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Durée maximale du quiz en secondes.'),
        ),
    ]
