# Generated by Django 6.1 on 2026-08-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quizprogress_time_limit_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Durée maximale du quiz en secondes.'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('ABANDONED', 'Abandonnée'), ('TIME_EXPIRED', 'Temps écoulé')], default='IN_PROGRESS', max_length=20),
        ),
    ]
